language: c
install:
  - ./.travis/install.sh
script: /bin/true
env:
  global:
    - secure: "1qAHFxnz0gIxMMl9DAVzoPvVSpOacWT2G6ItcaoaVe1r4OANzpoHBlbyHX2I/1KFe+BohzjS9kXA4NrlPaL81qfvu9E6qZ9yai/+0gHdzZttB2uvdyFXyDVye3CHHDlYMfRRQf6C+eYs5CKeedWq9Q3arO1GyAWiL9RcW1466sg="
addons:
  coverity_scan:
    project:
      name: "vincentbernat/lldpd"
      description: "implementation of IEEE 802.1ab (LLDP)"
    notification_email: bernat@luffy.cx
    build_command_prepend: ./.travis/run.sh
    build_command: make
    branch_pattern: coverity_scan
